In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error,r2_score
    
import pickle
import json

In [2]:
md=pd.read_csv('medical_insurance.csv')
md

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
md.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
md['sex'].value_counts()

male      676
female    662
Name: sex, dtype: int64

In [5]:
md.replace({'male':1,'female':0},inplace=True)

In [6]:
md['sex']

0       0
1       1
2       1
3       1
4       1
       ..
1333    1
1334    0
1335    0
1336    0
1337    0
Name: sex, Length: 1338, dtype: int64

In [7]:
md['smoker'].value_counts()

no     1064
yes     274
Name: smoker, dtype: int64

In [8]:
md.replace({'yes':1,'no':0},inplace=True)

In [9]:
md['smoker'].value_counts()

0    1064
1     274
Name: smoker, dtype: int64

In [10]:
md['region'].value_counts().to_dict()

{'southeast': 364, 'southwest': 325, 'northwest': 325, 'northeast': 324}

In [11]:
md = pd.get_dummies(md,columns=['region'])

In [12]:
md

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400                 0   
1      18    1  33.770         1       0   1725.55230                 0   
2      28    1  33.000         3       0   4449.46200                 0   
3      33    1  22.705         0       0  21984.47061                 0   
4      32    1  28.880         0       0   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       0  10600.54830                 0   
1334   18    0  31.920         0       0   2205.98080                 1   
1335   18    0  36.850         0       0   1629.83350                 0   
1336   21    0  25.800         0       0   2007.94500                 0   
1337   61    0  29.070         0       1  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [13]:
md.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   sex               1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   uint8  
 7   region_northwest  1338 non-null   uint8  
 8   region_southeast  1338 non-null   uint8  
 9   region_southwest  1338 non-null   uint8  
dtypes: float64(2), int64(4), uint8(4)
memory usage: 68.1 KB


In [14]:
md['children'].value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

## Train test split

In [15]:
x=md.drop('charges', axis=1)
x
y=md['charges']

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

## model training

In [17]:
insurance_model=LinearRegression()
insurance_model.fit(x_train,y_train)

LinearRegression()

In [18]:
#  Testing Data Evaluation
y_pred = insurance_model.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
print('MSE :', mse)

rmse = np.sqrt(mse)
print('RMSE :',rmse)

mae = mean_absolute_error(y_test, y_pred)
print('MAE :', mae)

r2_value = r2_score(y_test, y_pred)
print('R-Squared Value :', r2_value)

MSE : 38304871.348685905
RMSE : 6189.092934242134
MAE : 4279.860834219365
R-Squared Value : 0.7449415564623687


In [19]:
# Training Data Evaluation
y_pred_train=insurance_model.predict(x_train)

In [20]:
MSE=mean_squared_error(y_train,y_pred_train)
print('MSE_train :',MSE)

RMSE = np.sqrt(MSE)
print('RMSE :',RMSE)

MAE=mean_absolute_error(y_train,y_pred_train)
print('MSE_train :',MAE)

R2_SCORE=r2_score(y_train,y_pred_train)
print('R2 score :',R2_SCORE)

MSE_train : 36100283.869831294
RMSE : 6008.351177305742
MSE_train : 4138.842762471065
R2 score : 0.7520187377309014


## testing on single row

In [21]:
x.head(1).T

0
age               19.0
sex                0.0
bmi               27.9
children           0.0
smoker             1.0
region_northeast   0.0
region_northwest   0.0
region_southeast   0.0
region_southwest   1.0

In [22]:
test_array=np.array([55,1,27,1,1,0,1,0,0],ndmin=2)
test_array

array([[55,  1, 27,  1,  1,  0,  1,  0,  0]])

In [23]:
insurance_model.predict(test_array)

c:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([35128.32930255])

In [24]:
project_data={'sex':{'male':1,'female':0},
             'smoker':{'yes':1,'no':0},
             'column_names':list(x.columns)}
project_data

{'sex': {'male': 1, 'female': 0},
 'smoker': {'yes': 1, 'no': 0},
 'column_names': ['age',
  'sex',
  'bmi',
  'children',
  'smoker',
  'region_northeast',
  'region_northwest',
  'region_southeast',
  'region_southwest']}

In [25]:
project_data['column_names']

['age',
 'sex',
 'bmi',
 'children',
 'smoker',
 'region_northeast',
 'region_northwest',
 'region_southeast',
 'region_southwest']

In [26]:
column_names=x.columns
column_names

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [27]:
region='southwest'
region='region_'+ region
region_index=np.where(column_names==region)[0][0]
region_index

8

In [28]:
test_array=np.zeros(x.shape[1])
test_array[0]=age=32
test_array[1]=project_data['sex']['male']
test_array[2]=bmi=21.5
test_array[3]=children=2
test_array[4]=project_data['smoker']['no']
test_array[region_index]=1
test_array

array([32. ,  1. , 21.5,  2. ,  0. ,  0. ,  0. ,  0. ,  1. ])

In [29]:
cost=insurance_model.predict([test_array])

c:\Users\Admin\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [30]:
print('cost for medical_insurance== Rs.',round(cost[0],2))

cost for medical_insurance== Rs. 3627.15


In [31]:
with open('medical_model.pkl','wb')as f:
    pickle.dump(insurance_model,f)

In [32]:
with open('project_data.json','w')as f:
    json.dump(project_data,f)